# Generated by Django 6.0.5 on 2026-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0003_best_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershipbestsupplier',
            name='reason',
            field=models.TextField(help_text='Why this supplier was selected or why it changed.'),
        ),
    ]
