# Generated by Django 6.0.5 on 2026-07-03 03:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.ForeignKey(blank=True, help_text='Leave blank to apply this promotion to all cars from this supplier.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_promotions', to='cars.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Promotion',
                'verbose_name_plural': 'Supplier Promotions',
            },
        ),
    ]
