# Generated by Django 6.0.5 on 2026-06-08 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('ford', 'Ford'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('volkswagen', 'Volkswagen'), ('nissan', 'Nissan')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2026)])),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('red', 'Red'), ('blue', 'Blue'), ('gray', 'Gray'), ('green', 'Green')], max_length=50)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], max_length=20)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
